config/routes.rb
Rails.application.routes.draw do
  resources :books, path: "knjige"
  resources :genres, path: "zanri"
  resources :authors, path: "avtorji"
  resources :sessions, only: [:create, :new]

  get '', to: redirect('/knjige')

  resources :sessions, only: [:create, :new] do
    collection do
      get :logout
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  before_action :authentication_required!

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all.order(:name)
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Žanr uspešno ustvarjen.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Žanr uspešno posodobljen.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Žanr uspešno izbrisan.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre, local: true) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2>Žanra ni bilo mogoče shraniti.</h2>

      <ul>
        <% genre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Ime" %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Uredi žanr</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Prikaži', @genre, class: 'add-button' %>
<%= link_to 'Nazaj', genres_path, class: 'add-button' %>

app/views/genres/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Žanri</h1>

<table>
  <thead>
    <tr>
      <th>Ime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= link_to 'Prikaži', genre %></td>
        <td><%= link_to 'Uredi', edit_genre_path(genre) %></td>
        <td><%= link_to 'Izbriši', genre, method: :delete, data: { confirm: 'Ste prepričani, da želite izbrisati žanr?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj žanr', new_genre_path, class: 'add-button' %>

app/views/genres/new.html.erb
<h1>Nov žanr</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Nazaj', genres_path, class: 'add-button' %>

app/views/genres/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>Ime:</strong>
  <%= @genre.name %>
</p>

<%= link_to 'Uredi', edit_genre_path(@genre), class: 'add-button' %>
<%= link_to 'Nazaj', genres_path, class: 'add-button' %>