config/routes.rb
Rails.application.routes.draw do
  resources :books, path: "knjige"
  resources :genres, path: "zanri"
  resources :authors, path: "avtorji"
  resources :sessions, only: [:create, :new]

  get '', to: redirect('/knjige')

  resources :sessions, only: [:create, :new] do
    collection do
      get :logout
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :authentication_required!

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all.order(:name)
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Avtor uspešno ustvarjen.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Avtor uspešno posodobljen.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Avtor uspešno izbrisan.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2>Avtorja ni bilo mogoče shraniti.</h2>

      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Ime" %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Uredi avtorja</h1>

<%= render 'form', author: @author %>

<%= link_to 'Prikaži', @author, class: 'add-button' %>
<%= link_to 'Nazaj', authors_path, class: 'add-button' %>

app/views/authors/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Avtorji</h1>

<table>
  <thead>
    <tr>
      <th>Ime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to 'Prikaži', author %></td>
        <td><%= link_to 'Uredi', edit_author_path(author) %></td>
        <td><%= link_to 'Izbriši', author, method: :delete, data: { confirm: 'Ste prepričani, da želite izbrisati avtorja?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj avtorja', new_author_path, class: 'add-button' %>

app/views/authors/new.html.erb
<h1>Nov avtor</h1>

<%= render 'form', author: @author %>

<%= link_to 'Nazaj', authors_path, class: 'add-button' %>

app/views/authors/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>Ime:</strong>
  <%= @author.name %>
</p>

<%= link_to 'Uredi', edit_author_path(@author), class: 'add-button' %>
<%= link_to 'Nazaj', authors_path, class: 'add-button' %>