config/routes.rb
Rails.application.routes.draw do
  resources :books, path: "knjige"
  resources :genres, path: "zanri"
  resources :authors, path: "avtorji"
  resources :sessions, only: [:create, :new]

  get '', to: redirect('/knjige')

  resources :sessions, only: [:create, :new] do
    collection do
      get :logout
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :genre, optional: true
  belongs_to :author

  validates :title, :internal_number, presence: true
  validates :internal_number, numericality: { only_integer: true }
  validates :internal_number, uniqueness: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authentication_required!, only: [:show, :create, :new, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @raw_query_param = params[:query]
    where_query = "
      REPLACE(REPLACE(REPLACE(REPLACE(LOWER(books.title), 'č', 'c'), 'š', 's'), 'ž', 'z'), ' ', '') LIKE :query OR
      REPLACE(REPLACE(REPLACE(REPLACE(LOWER(authors.name), 'č', 'c'), 'š', 's'), 'ž', 'z'), ' ', '') LIKE :query OR
      REPLACE(REPLACE(REPLACE(REPLACE(LOWER(genres.name), 'č', 'c'), 'š', 's'), 'ž', 'z'), ' ', '') LIKE :query
    "
    query_param = @raw_query_param.delete(' ').downcase.gsub('č', 'c').gsub('š', 's').gsub('ž', 'z') rescue ''

    if is_int? @raw_query_param
      where_query = where_query + "OR books.internal_number = :raw_query"
    end

    @books = Book.all
      .left_joins(:author, :genre)
      .where(
        where_query,
        {
          query: "%#{query_param}%",
          raw_query: @raw_query_param,
        }
      )
      .order(is_borrowed: :desc, title: :asc)

    @total_books_count = Book.all.count
    @borrowed_books_count = Book.all
      .where(is_borrowed: true)
      .count

  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    @raw_author_name = @book.author.name
  end

  # POST /books
  # POST /books.json
  def create
    @raw_author_name = params.require(:book)[:author_name]
    author_name = @raw_author_name.delete(' ').downcase.gsub('č', 'c').gsub('š', 's').gsub('ž', 'z') rescue ''
    where_query = "REPLACE(REPLACE(REPLACE(REPLACE(LOWER(authors.name), 'č', 'c'), 'š', 's'), 'ž', 'z'), ' ', '') = :author_name"

    authors = Author.where(
      where_query,
      { author_name: author_name }
    )

    if authors.size == 0
      new_author = Author.new(name: @raw_author_name)
      if new_author.save
        author_id = new_author.id
      else
        author_id = nil
      end
    else
      author_id = authors[0].id
    end

    @book = Book.new(book_params.merge(:author_id => author_id))

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Knjiga uspešno ustvarjena.' }
        format.json { render :show, status: :created, location: @book }
      else
        if new_author
          new_author.destroy!
        end

        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Knjiga uspešno posodobljena.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Knjiga uspešno izbrisana.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def is_int?(str)
      !!Integer(str)
    rescue ArgumentError, TypeError
      false
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:internal_number, :title, :is_borrowed, :genre_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2>Knjige ni bilo mogoče shraniti.</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :internal_number %>
    <%= form.number_field :internal_number %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author_name %>
    <%= form.text_field :author_name, value: @raw_author_name %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.collection_select :genre_id, Genre.order(:name), :id, :name, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :is_borrowed %>
    <%= form.check_box :is_borrowed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Uredi knjigo</h1>

<%= render 'form', book: @book %>

<%= link_to 'Prikaži', @book, class: 'add-button' %>
<%= link_to 'Nazaj', books_path, class: 'add-button' %>

app/views/books/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<div class="books__title-wrapper">
  <h1>Knjige</h1>

  <div class="books__count">
    <div class="books__count-stat">
      <div class="books__count-stats-text">Število vseh knjig: </div>
      <div class="books__count-stats-number"><%= @total_books_count %></div>
    </div>

    <div class="books__count-stat">
      <div class="books__count-stats-text">Število izposojenih knjig: </div>
      <div class="books__count-stats-number"><%= @borrowed_books_count %></div>
    </div>
  </div>
</div>

<div class="books__search">
  <input id="books-search-input" class="books__search-input" placeholder="Išči knjige" value="<%= @raw_query_param %>"/>
  <div id="books-search-button" class="books__search-button">Išči</div>
</div>

<table class="books__table">
  <thead>
    <tr>
      <th>Interna številka</th>
      <th>Naslov</th>
      <th>Avtor</th>
      <th>Žanr</th>
      <th>Izposojena</th>
      <% if session[:current_user] %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr class="book <%= book.is_borrowed ? 'book--borrowed' : '' %>">
        <td><%= book.internal_number %></td>
        <td><%= book.title %></td>
        <td><%= book.author.name %></td>
        <td><%= book.genre.name if book.genre %></td>
        <td><%= book.is_borrowed ? 'Da' : 'Ne' %></td>

        <% if session[:current_user] %>
          <td><%= link_to 'Prikaži', book %></td>
          <td><%= link_to 'Uredi', edit_book_path(book) %></td>
          <td><%= link_to 'Izbriši', book, method: :delete, data: { confirm: 'Ste prepričani, da želite izbrisati knjigo?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/books/new.html.erb
<h1>Nova knjiga</h1>

<%= render 'form', book: @book %>

<%= link_to 'Nazaj', books_path, class: 'add-button' %>

app/views/books/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>Interna številka:</strong>
  <%= @book.internal_number %>
</p>

<p>
  <strong>Naslov:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Avtor:</strong>
  <%= @book.author.name %>
</p>

<p>
  <strong>Žanr:</strong>
  <%= @book.genre.name if @book.genre %>
</p>

<p>
  <strong>Izposojena:</strong>
  <%= @book.is_borrowed ? 'Da' : 'Ne' %>
</p>

<%= link_to 'Uredi', edit_book_path(@book), class: 'add-button' %>
<%= link_to 'Nazaj', books_path, class: 'add-button' %>