config/routes.rb
Rails.application.routes.draw do
  resources :books, path: "knjige"
  resources :genres, path: "zanri"
  resources :authors, path: "avtorji"
  resources :sessions, only: [:create, :new]

  get '', to: redirect('/knjige')

  resources :sessions, only: [:create, :new] do
    collection do
      get :logout
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Knjigored</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon-book.ico') %>
  </head>

  <body>
    <div class="header">
      <div class="header__section">
        <%= link_to 'Knjigored', books_path, class: 'header__button header__button--main' %>
      </div>

      <div class="header__section header__section--right">
        <% if session[:current_user] %>
          <%= link_to 'Nova knjiga', new_book_path, class: 'header__button' %>
          <%= link_to 'Domov', books_path, class: 'header__button' %>
          <%= link_to 'Odjava', logout_sessions_path, class: 'header__button' %>
        <% else %>
          <%= link_to 'Prijava', '/sessions/new', class: 'header__button' %>
        <% end %>
      </div>
    </div>

    <div class="main-wrapper">
      <%= yield %>
    </div>
  </body>
</html>